### ISSUE TITLE
Not able to use multiple API Keys

### ISSUE THREAD

**Issue by SicorDev** [sup7even/mailchimp#10]
Could you please add a way to use multiple API Keys in your extension ?
You could move the extensionmanager setting to a typoscript setting, then we could set the api-key for each domain individually.

Thanks,
Sicor DevTeam

**Comment by georgringer** [comment]
wanna sponsor that or do a PR?

**Comment by SicorDev** [comment]
The last approach wasn't very usefull.
We decided to to change it up and add a option in the plugin flexform to override the api key.

**Comment by georgringer** [comment]
i did a different way and merged, therefore I am closing this
