### ISSUE TITLE
Possibility to sign out?

### ISSUE THREAD

**Issue by mgrn0** [sup7even/mailchimp#13]
Is there a possibility to use the plugin to sign *out* of a mailchimp newsletter list, too - through submitting a registered email address, for example?

Maybe I have overseen it, but a quick look at the manual did not show anything; and I know, there are sunsubscribe-links in every mail/newsletter, but customers are lazy.. ;)

**Comment by georgringer** [comment]
not possible currently but could be done by creating a separate plugin. wanna sponsor that or code it?
