### ISSUE TITLE
can i use only email fields in subscription form?

### ISSUE THREAD

**Issue by pravin-vavadiya** [sup7even/mailchimp#16]
I want to display only email fields in my subscription form.  but when i use only email fields then getting response like below. if i use firstName lastName with email fields then it's working.

> > An error has occurred, we are sorry!

Any one help me ?
How can i remove this two fields in my in subscription form.
Thanks in advance :)

**Comment by kersten** [comment]
You need to overwrite the template ```typo3conf/ext/mailchimp/Resources/Private/Templates/Form/Index.html```

You can do this in a ts template like:

```TypoScript
plugin.tx_mailchimp {
    view {
        templateRootPaths {
            0 = typo3conf/ext/mailchimp/Resources/Private/Templates/
            1 = typo3conf/ext/YOUR_EXT/Resources/Private/Templates/Mailchimp/
        }
    }
}
```

**Comment by georgringer** [comment]
I would suggest to keep the merge fields in mailchimp and then you can just remove the fields.

**Comment by kersten** [comment]
I don't know how it was setup on the MailChimp site, but as default firstName and lastName are not mandatory fields. If they are setup to be mandatory then the fields need to be changed in the List settings.

**Comment by pravin-vavadiya** [comment]
@georgringer 

How can i merge fields?.
For temporary i resolved this issue using display none in both of this fields in Template file.
