### ISSUE TITLE
Mailchimp use User_Int

### ISSUE THREAD

**Issue by ohm-meter** [sup7even/mailchimp#42]
The Admin Console Says that Malchimp use User_int

![mailchimp](https://user-images.githubusercontent.com/49782166/138093081-7e919f43-dc1d-4d65-849e-918a1406d23d.png)

Is this correct ? Will this not kill the Cache ?

Cheers Oliver

**Comment by georgringer** [comment]
of course the full page can't be cached but as long as you don't have the form on every page it will be fine.
having a USER and dyamically convert it to a USER_INT is always a challenge.
